CREATE schema if not exists agenda;
  
CREATE TABLE TAB_PROFILE (
  id bigint generated by default as identity, 
  name varchar(60), 
  primary key (id)
);

CREATE TABLE TAB_USER (
  id bigint generated by default as identity, 
  name varchar(255),
  password varchar(255), 
  username varchar(255),
  access_token varchar(60),
  enabled boolean,
  primary key (id)
);

CREATE TABLE TAB_USER_PROFILE (
  fk_id_user bigint not null, 
  fk_id_profile bigint not null
);



CREATE TABLE TAB_CONTACT (
   id bigint generated by default as identity,
   name varchar(60), 
   email varchar(100),
   home_phone varchar(60),  
   cell_phone varchar(60), 
   fk_id_user  bigint not null,
   primary key (id),
 );


alter table TAB_USER_PROFILE 
add constraint FKbue5w2clcyki08fcbhklq3ne1 foreign key (fk_id_profile) 
references TAB_PROFILE ;

alter table TAB_USER_PROFILE 
add constraint FKocp5x2w1ixasajgxprdnaudfb foreign key (fk_id_user) 
references TAB_USER;

alter table TAB_CONTACT 
add constraint FKocp5x2w1ixasajgxprdnaudf2 foreign key (fk_id_user) 
references TAB_USER;






